# docker-compose.yml
version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: battery_sim
    ports:
      - "5432:5432"
